name: ClansOffline
version: ${project.version}
main: com.github.sanctum.clansoffline.bukkit.ClansJavaPlugin
api-version: 1.13
depend: [ Labyrinth ]
authors: [ Hempfest ]
description: A smaller port to clans [pro] allowing for use in offline mode.
